- .github/workflows/update_bridge_hub.yml
> add bridge update hub file

- src/bridge_godot_python.py
- fixed the bridge file where it had format messup
> fixed the messup code format

- .github/workflows/bv_web_export.yml
> added export

- .github/workflows/version_updates.yml
- src/bridge_godot_python.py
This PR syncs with latest Neuraville Inc. development code.
> Updates from Neuraville Inc.

- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/Mapping_Views/GeneralMappingEditor.tscn
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/Mapping_Views/Prefab_Mapping.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/Mapping_Views/Prefab_Mapping.tscn
PSP in UI can only be positive, negativity is controlled now by a new inhibitory switch
> add inhibitory switch for PSP mapping

- godot_source/Feagi-Godot-Interface/UI/Brain_Visualizer/Camera3D.gd
- godot_source/Feagi-Godot-Interface/UI/Graph/NodeGraph.tscn
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/WindowEditMappingDefinition.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Quick_Cortical_Menu/QuickCorticalMenu.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/BaseWindowPanel.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/TitleBar/TitleBar.tscn
> Fix window ordering

- godot_source/Feagi-Godot-Interface/UI/Brain_Visualizer/Camera3D.gd
- godot_source/Feagi-Godot-Interface/UI/Graph/NodeGraph.tscn
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/WindowEditMappingDefinition.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Quick_Cortical_Menu/QuickCorticalMenu.gd
fix signal not updating to the correct cortical area
> Mapping view update fix

- godot_source/Feagi-Godot-Interface/Core/Cache-Objects/Cortical-Areas/BaseCorticalArea.gd
- godot_source/Feagi-Godot-Interface/UI/Graph/CorticalNode/Connection/CB_Line_Shader.gdshader
- godot_source/Feagi-Godot-Interface/UI/Graph/CorticalNode/Connection/InterCorticalConnection.gd
- godot_source/Feagi-Godot-Interface/UI/Graph/CorticalNodeGraph.gd
- godot_source/Feagi-Godot-Interface/UI/Universal/UIManager.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/WindowEditMappingDefinition.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/DropDown/ToggleImageDropdown/ToggleImageDropDown.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/WindowManager.gd
CB lines now outline when mapping editor selects them
addresses points in https://github.com/feagi/brain-visualizer/issues/101
> Highlighting cb lines

- godot_source/Feagi-Godot-Interface/Core/FEAGIRequests.gd
- godot_source/Feagi-Godot-Interface/Core/FEAGIUtils.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/API/APIRequestWorker.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/CallList.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/ResponseProxyFunctions.gd
- godot_source/Feagi-Godot-Interface/FeagiRoot.tscn
- godot_source/Feagi-Godot-Interface/UI/Brain_Visualizer/Camera3D.gd
- godot_source/Feagi-Godot-Interface/UI/Graph/CorticalNode/CorticalNode.gd
- godot_source/Feagi-Godot-Interface/UI/Graph/CorticalNodeGraph.gd
- godot_source/Feagi-Godot-Interface/UI/Universal/UIManager.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Configurable_Popup/definitions/ConfigurablePopupDefinition.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/WindowCorticalProperties.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/WindowCorticalProperties.tscn
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Create_Cortical_Area/Parts/PartSpawnCorticalAreaIOPU.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Create_Cortical_Area/WindowCreateCorticalArea.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Developer_Options/Parts/WindowDeveloperOptionsPartCameraAnimations.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Developer_Options/Parts/WindowDeveloperOptionsPartCameraAnimations.tscn
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Developer_Options/WindowDeveloperOptions.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Developer_Options/WindowDeveloperOptions.tscn
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Quick_Cortical_Menu/QuickCorticalMenu.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/BaseWindowPanel.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/DropDown/ToggleImageDropdown/ToggleImageDropDown.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/MultiItemCollapsible/MultiItemCollapsible.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/Scroll/GenericTextIDScroll/GenericTextIDScroll.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/TitleBar/TitleBar.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/WindowManager.gd
Ensure Developer mode is enabled under the FeagiRoot Scene, under the UI node. Set your desired key (default \)
When in godot, hit \ to open up developer menu. move camera to desired position and click "Add current position"). Set transition time you desire and move camera to next position and click "Add current position" again. Repeat until happy. Define animation interp settings and click Export to show the generated animation json. Hit Play to play the current Json Animation
> Camera Animation system

- godot_source/Feagi-Godot-Interface/Core/FEAGIRequests.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/API/APIRequestWorker.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/CallList.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/ResponseProxyFunctions.gd
- godot_source/Feagi-Godot-Interface/UI/Brain_Visualizer/Camera3D.gd
- godot_source/Feagi-Godot-Interface/UI/Graph/CorticalNode/CorticalNode.gd
- godot_source/Feagi-Godot-Interface/UI/Graph/CorticalNodeGraph.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Configurable_Popup/definitions/ConfigurablePopupDefinition.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/WindowCorticalProperties.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Create_Cortical_Area/Parts/PartSpawnCorticalAreaIOPU.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Create_Cortical_Area/WindowCreateCorticalArea.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Quick_Cortical_Menu/QuickCorticalMenu.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/BaseWindowPanel.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/DropDown/ToggleImageDropdown/ToggleImageDropDown.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/MultiItemCollapsible/MultiItemCollapsible.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/Scroll/GenericTextIDScroll/GenericTextIDScroll.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Elements/TitleBar/TitleBar.gd
cleaned up old error checking code
cleaned up a whole bunch of warnings
> Cleanup old error checking

- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Clone_Cortical_Area/WindowCloneCorticalArea.gd
change offset of copy areas as per https://github.com/feagi/brain-visualizer/issues/119
> change offset of cloned areas to only move X wise 10 units

- godot_source/Feagi-Godot-Interface/UI/Graph/CorticalNodeGraph.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/Parts/CorticalPropertiesBottomMapping.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/Parts/CorticalPropertiesConnections.tscn
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/Mapping_Views/GeneralMappingEditor.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/WindowEditMappingDefinition.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Mapping_Definition/WindowEditMappingDefinition.tscn
fix left bar missing buttons
fix other crashes related to mapping window
> Fix left bar missing add buttons

- godot_source/Feagi-Godot-Interface/Core/Networking/NetworkBootStrap.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/Parts/CorticalPropertiesPostSynapticPotentialParameters.tscn
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/WindowCorticalProperties.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/QuickConnect/WindowQuickConnect.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/QuickConnect/WindowQuickConnect.tscn
> Fix qc scaling

- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/Parts/CorticalPropertiesNeuronFiringParameters.tscn
fix issue https://github.com/feagi/brain-visualizer/issues/148
> add missing signal

- godot_source/Feagi-Godot-Interface/Core/Networking/API/AddressList.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/CallList.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/ResponseProxyFunctions.gd
- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/Parts/CorticalPropertiesNeuronFiringParameters.tscn
fixes issue https://github.com/feagi/brain-visualizer/issues/150
also fixes some formatting issues with utilizing these endpoints
> Fix insight path

- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Create_Morphology/WindowCreateMorphology.gd
resolve https://github.com/feagi/brain-visualizer/issues/142
> add notifications

- godot_source/Feagi-Godot-Interface/UI/Windows/Draggable_Windows/Cortical_Properties/Parts/CorticalPropertiesCorticalAreaMonitoring.gd
fix https://github.com/feagi/brain-visualizer/issues/154
> godot, please let me override these methods so I dont have to do these ridiculous workarounds

- godot_source/Feagi-Godot-Interface/Core/Cache-Objects/Morphologies/Morphology.gd
- godot_source/Feagi-Godot-Interface/Core/Cache-Objects/Morphologies/Pattern-Variables/PatternVector3Pairs.gd
- godot_source/Feagi-Godot-Interface/Core/Cache-Objects/MorphologiesCache.gd
- godot_source/Feagi-Godot-Interface/Core/FEAGIRequests.gd
- godot_source/Feagi-Godot-Interface/Core/FEAGIUtils.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/API/APIRequestWorker.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/API/AddressList.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/CallList.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/ResponseProxyFunctions.gd
for the time being, prevent a crash on feagi disconnect. further changes need more time
> Fix feagi down crash

- godot_source/Feagi-Godot-Interface/Core/Cache-Objects/Morphologies/Morphology.gd
- godot_source/Feagi-Godot-Interface/Core/Cache-Objects/Morphologies/Pattern-Variables/PatternVector3Pairs.gd
- godot_source/Feagi-Godot-Interface/Core/Cache-Objects/MorphologiesCache.gd
- godot_source/Feagi-Godot-Interface/Core/FEAGIRequests.gd
- godot_source/Feagi-Godot-Interface/Core/FEAGIUtils.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/API/AddressList.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/CallList.gd
- godot_source/Feagi-Godot-Interface/Core/Networking/ResponseProxyFunctions.gd
change morphology cache init with a new endpoint that gives all details. should fix issue related to ineditable morphologies
> New morphology startup

- godot_source/BrainVisualizer/UI/BrainMonitor/brain_visualizer_main_script.gd
- a fix for this: https://github.com/feagi/brain-visualizer/issues/188
> Feature fix yd dev

- godot_source/Utils/JavaScriptIntegrations.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/ConfigScripts/FeagiEndpointDetails.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/FeagiCore.gd
switched javascript to using fallback values instead of rejecting when any parameter is missing
added additional logging
> Javascript endpoint with fallback

- godot_source/BrainVisualizer/BrainVisualizer.tscn
- godot_source/BrainVisualizer/UI/Windows/Create_Cortical_Area/WindowCreateCorticalArea.gd
- godot_source/BrainVisualizer/UI/sky.tres
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/CorticalAreasCache.gd
address https://github.com/feagi/brain-visualizer/issues/224
> fix incorrect substring search function name

- godot_source/BrainVisualizer/BrainVisualizer.gd
- godot_source/BrainVisualizer/Configs/feagi_default_settings.tres
- godot_source/BrainVisualizer/UI/BrainMonitor/3d_indicator.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBAbstractNode.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBNodeConnectableBase.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CircuitBuilder.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/TempSplit.gd
- godot_source/BrainVisualizer/UI/GenericElements/Scroll/ScrollGeneric/ScrollSectionGeneric.gd
- godot_source/BrainVisualizer/UI/Notifications/NotificationSystem.gd
- godot_source/BrainVisualizer/UI/Top_Bar/StateIndicator/StateInidicator.gd
- godot_source/BrainVisualizer/UI/UIManager.gd
- godot_source/BrainVisualizer/UI/Windows/AdvancedCorticalProperties/AdvancedCorticalProperties.gd
- godot_source/BrainVisualizer/UI/Windows/AdvancedCorticalProperties/AdvancedCorticalProperties.tscn
- godot_source/BrainVisualizer/UI/Windows/CreateMorphology/WindowCreateMorphology.gd
- godot_source/Utils/JavaScriptIntegrations.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/ConfigScripts/FeagiEndpointDetails.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/ConfigScripts/FeagiGeneralSettings.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/FEAGIRequests.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/FeagiCore.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/CorticalAreas/CorticalProperties/CorticalPropertyNeuronFiringParameters.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/FEAGILocalCache.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/API/APIRequestWorker.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/API/APIRequestWorker.tscn
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/API/APIRequestWorkerDefinition.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/API/FEAGIHTTPAPI.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/FEAGINetworking.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/WebSocket/FEAGIWebSocketAPI.gd
Major rework on core state machine. Things should be much easier to understand now + much better fallback behaviors
fix https://github.com/feagi/brain-visualizer/issues/330
fix? https://github.com/feagi/brain-visualizer/issues/336
fix https://github.com/feagi/brain-visualizer/issues/329
fix https://github.com/feagi/brain-visualizer/issues/333
fix https://github.com/feagi/brain-visualizer/issues/331
set advanced mode to true by default (method to do this is stupid, some things still need to be reworked there)
> Refactor connection handler

- godot_source/BrainVisualizer/UI/Top_Bar/TopBar.gd
- godot_source/BrainVisualizer/UI/Windows/CloneCorticalArea/WindowCloneCorticalArea.gd
- godot_source/BrainVisualizer/UI/Windows/CreateCorticalArea/Parts/PartSpawnCorticalAreaIOPU.gd
- godot_source/BrainVisualizer/UI/Windows/CreateCorticalArea/WindowCreateCorticalArea.gd
- godot_source/BrainVisualizer/UI/Windows/CreateCorticalArea/WindowCreateCorticalArea.tscn
- godot_source/BrainVisualizer/UI/Windows/MappingEditor/MappingEditorRowGeneric.gd
- godot_source/project.godot
addresses....
https://github.com/feagi/brain-visualizer/issues/352
https://github.com/feagi/brain-visualizer/issues/355
https://github.com/feagi/brain-visualizer/issues/356
> More fixes!

- godot_source/BrainVisualizer/UI/Top_Bar/TopBar.gd
> stop blanking of top bar counts on resets for now

- godot_source/BrainVisualizer/UI/GenericElements/Scroll/ScrollGeneric/ScrollSectionGeneric.gd
- godot_source/BrainVisualizer/UI/Windows/AdvancedCorticalProperties/AdvancedCorticalProperties.tscn
- godot_source/BrainVisualizer/UI/Windows/CloneCorticalArea/WindowCloneCorticalArea.gd
WIP
fix https://github.com/feagi/brain-visualizer/issues/362
fix https://github.com/feagi/brain-visualizer/issues/368
fix https://github.com/feagi/brain-visualizer/issues/363
fix https://github.com/feagi/brain-visualizer/issues/367
fix https://github.com/feagi/brain-visualizer/issues/361
fix https://github.com/feagi/brain-visualizer/issues/365
> Vacation bugs!

- godot_source/BrainVisualizer/UI/CircuitBuilder/CBNodeBrainRegion/CBNodeRegion.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBNodeConnectableBase.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBNodeCorticalArea/CBNodeCorticalArea.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CircuitBuilder.gd
- godot_source/BrainVisualizer/UI/UIManager.gd
- godot_source/BrainVisualizer/UI/UIView/UITabContainer/UITabContainer.gd
Butt-Ugly hack to fix subregion selection for now
fix https://github.com/feagi/brain-visualizer/issues/370
> Redo selection logic

- godot_source/BrainVisualizer/UI/Windows/OptionsMenu/WindowOptionsMenu.gd
- godot_source/BrainVisualizer/UI/Windows/OptionsMenu/WindowOptionsMenu.tscn
- godot_source/addons/FeagiCoreIntegration/FeagiCore/FEAGIRequests.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/FEAGILocalCache.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/API/FEAGIHTTPAddressList.gd
adds https://github.com/feagi/brain-visualizer/issues/359
fixes https://github.com/feagi/brain-visualizer/issues/374
> Feature plasticity queue

- godot_source/BrainVisualizer/UI/BrainMonitor/brain_visualizer_main_script.gd
- godot_source/BrainVisualizer/UI/BrainMonitor/cortical_area_box.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBLine/CBLineInterTerminal.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/FEAGIRequests.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/CorticalAreas/IPUCorticalArea.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/CorticalAreas/OPUCorticalArea.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/FEAGILocalCache.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/API/FEAGIHTTPAddressList.gd
more labels
fix BM titles getting too wide
addresses:
https://github.com/feagi/brain-visualizer/issues/394
https://github.com/feagi/brain-visualizer/issues/392
mitigation for:
https://github.com/feagi/brain-visualizer/issues/393
> More fixes again

- godot_source/BrainVisualizer/UI/BrainMonitor/brain_visualizer_main_script.gd
- godot_source/BrainVisualizer/UI/BrainMonitor/cortical_area_box.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBLine/CBLineInterTerminal.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBNodeBrainRegion/CBNodeRegion.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBNodeConnectableBase.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CBNodeCorticalArea/CBNodeCorticalArea.gd
- godot_source/BrainVisualizer/UI/CircuitBuilder/CircuitBuilder.gd
- godot_source/BrainVisualizer/UI/UIManager.gd
- godot_source/BrainVisualizer/UI/UIView/UITabContainer/UITabContainer.gd
- godot_source/BrainVisualizer/UI/Windows/QuickConnect/WindowQuickConnect.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/FEAGIRequests.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/CorticalAreas/IPUCorticalArea.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/CorticalAreas/OPUCorticalArea.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/LocalCache/FEAGILocalCache.gd
- godot_source/addons/FeagiCoreIntegration/FeagiCore/Networking/API/FEAGIHTTPAddressList.gd
new selection system for CB only to fix various selection issues
> New selection system

- godot_source/BrainVisualizer/UI/UIView/UIView.gd
- godot_source/BrainVisualizer/UI/Windows/CloneCorticalArea/WindowCloneCorticalArea.tscn
- godot_source/BrainVisualizer/UI/Windows/ConfirmDeletion/WindowConfirmDeletion.tscn
- godot_source/BrainVisualizer/UI/Windows/QuickConnect/WindowQuickConnect.tscn
- godot_source/BrainVisualizer/UI/Windows/QuickMenu/WindowQuickMenu.gd
fix https://github.com/feagi/brain-visualizer/issues/424
fix https://github.com/feagi/brain-visualizer/issues/414
fix issue with crashing when opening quick connect with no selection
> Fix UI panel startup

- godot_source/BrainVisualizer/UI/Windows/OptionsMenu/WindowOptionsMenu.tscn
fix https://github.com/feagi/brain-visualizer/issues/428
> have buttons visible
